name: updatePosts
on:
  push:
    paths:
      - 'posts/**'
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: remotePull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd website
            git pull
